version: "3"

services:
  apisix:
    image: apache/apisix:3.1.0-debian
    ports:
      - "9080:9080"
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    env_file:
      - .env
  httpbin:
    image: kennethreitz/httpbin